[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
veilpay = "B5M7aRq3PXTNBzbrzxdgyN7hR2K6EsqE9L2hGid5EHst"
verifier = "ApgL98o4JA6ZJSR3G9X8HTymPCssztpKMYFZWohraotk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
